### ISSUE TITLE
WARN - opcode mismatch: pre: 1, now: 0

### ISSUE THREAD

**Issue by sonwh98** [bhauman/lein-figwheel#205] opened 2015-07-29 10:17 UTC
Wed Jul 29 11:13:27 BST 2015 [server-loop] WARN - opcode mismatch: pre: 1, now: 0
Eval timed out!

I get that error message when calling datascript transact! function from the figwheel repl 
See the save function at
see https://github.com/sonwh98/infamous/blob/master/src/com/kaicode/infamous.cljs 

To reproduce this run the figwheel repl on this project
https://github.com/sonwh98/cljs-famous-twitter

```
(in-ns 'com.kaicode.infamous)
(save {:foo/id "bar"})
```

**Comment by bhauman** [comment] 2015-07-29 15:46
This is an http-kit problem and has been referenced here 
https://github.com/bhauman/lein-figwheel/issues/194

**Comment by bhauman** [comment] 2015-08-05 19:14
I'm closing this as it's a duplicate of #194

**Closed by bhauman** 2015-08-05 19:14 UTC
