### ISSUE TITLE
Latest release of client redefines cljs at runtime.

### ISSUE THREAD

**Issue by Gonzih** [bhauman/lein-figwheel#86] opened 2015-02-09 16:05 UTC
Hi, I just noticed that when I'm trying to use cljs.core/enable-console-print! I'm getting is not a function errror. It only happens in namespace that also includes figwheel client initialization. I think issue is in `ensure-cljs-user function inside support/src/figwheel/client.cljs`. Can figwheel be less aggressive in this place?

Also this change generates warning in advanced compilation mode:

```
out/figwheel/client.js:440: WARNING - namespace cljs should not be redefined
cljs = {};
```

If I remove my enable-console-print! call error about undefined function happens somewhere in figwheel callback.

Thanks!

**Comment by bhauman** [comment] 2015-02-09 16:49
This seems like a good catch.

A couple of things: are you trying to use enable-console-print! from the REPL? I'm a little confused as to the context here.

Second, Figwheel is not meant to be included in an advanced build at all.

**Comment by Gonzih** [comment] 2015-02-09 16:52
I'm using console-print thing before figwheel is initialized but after it required. In advanced build I'm using macro to skip some code parts based on compilation target. So figwheel is not really initialized there, and I expect dead code elimination to do it's thing. As a quick fix I can propose to make all this checks lazy, so unless figwheel is initialized nothing happens. Also maybe you have better idea how to split different build and exclude some logic from them based on compilation target? Thanks.

**Comment by bhauman** [comment] 2015-02-09 17:22
Have you seen this:

https://gist.github.com/bhauman/cf5403efd142407355df

**Comment by Gonzih** [comment] 2015-02-09 18:41
Yes, I know about that. Will try to apply it. But so far my solution 
with macro worked fine fore me.

**Comment by bhauman** [comment] 2015-02-09 19:24
I'm definitely going to fix the figwheel side of this. :)

**Comment by Gonzih** [comment] 2015-02-09 19:36
Thanks a lot!

**Comment by bhauman** [comment] 2015-02-10 01:01
I'm not able to reproduce your error at all. Could you see if the minimal case still has this problem?

I'm getting rid of the warning producing code.  But I don't have any code that would blow away enable console print.  The code you reference never executes and I'm getting rid of it.

**Comment by cichli** [comment] 2015-02-10 07:48
@bhauman I did a `Cannot call method 'call' of undefined` error from somewhere in `enable-console-print!` earlier too, but can't replicate now with latest snapshot. This was using piggieback's `cljs-repl` and sidecar - which works really well by the way! Very quick to start and the whole thing has remained stable over several OS sleeps so far.

**Comment by Gonzih** [comment] 2015-02-10 10:15
Uh oh, I already rewrote big chunk of this code.
Anyway it's very interesting that code I was suspecting was not used at all.
Thank you for your time, I don't think it's necessary to spend a lot of 
time trying to figure out this issue
since I was kind of missusing figwheel by requiring it in advanced 
compilation mode.
But if you still need some snippet to reproduce this error I can try to 
make it.

**Comment by bhauman** [comment] 2015-02-10 15:48
I am still not able to reproduce this. I will unlikely be able to fix this with out an example :)

**Comment by Gonzih** [comment] 2015-02-10 16:28
I can't reproduce this error in figwheel project generated from scratch :)
https://github.com/Gonzih/tmp-figwheel-reproducing-something this is my 
best attempt so far.
I was able to get error that no *print-fn* is set for evaluation.
That's it. Sorry :(

**Comment by bhauman** [comment] 2015-02-12 19:29
This should be fixed now.

**Closed by bhauman** 2015-02-12 19:29 UTC
