### ISSUE TITLE
[lein-figwheel "0.3.1"] doesn't work

### ISSUE THREAD

**Issue by sdegutis** [bhauman/lein-figwheel#144] opened 2015-05-05 19:24 UTC
It just doesn't work.

~~~
$ lein new figwheel hello-world -- --reagent
Retrieving lein-figwheel/lein-figwheel/0.3.1/lein-figwheel-0.3.1.pom from clojars
Retrieving figwheel-sidecar/figwheel-sidecar/0.3.1/figwheel-sidecar-0.3.1.pom from clojars
Retrieving figwheel/figwheel/0.3.1/figwheel-0.3.1.pom from clojars
Retrieving clojurescript-build/clojurescript-build/0.1.6/clojurescript-build-0.1.6.pom from clojars
Retrieving lein-figwheel/lein-figwheel/0.3.1/lein-figwheel-0.3.1.jar from clojars
Retrieving clojurescript-build/clojurescript-build/0.1.6/clojurescript-build-0.1.6.jar from clojars
Retrieving figwheel-sidecar/figwheel-sidecar/0.3.1/figwheel-sidecar-0.3.1.jar from clojars
Retrieving figwheel/figwheel/0.3.1/figwheel-0.3.1.jar from clojars
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:340)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at stencil.core$loading__4958__auto__.invoke(core.clj:1)
	at stencil.core__init.load(Unknown Source)
	at stencil.core__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:340)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at leiningen.new.templates$loading__4958__auto__.invoke(templates.clj:11)
	at leiningen.new.templates__init.load(Unknown Source)
	at leiningen.new.templates__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:340)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at leiningen.new$loading__4958__auto__.invoke(new.clj:1)
	at leiningen.new__init.load(Unknown Source)
	at leiningen.new__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:340)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at leiningen.core.utils$require_resolve.invoke(utils.clj:80)
	at leiningen.core.utils$require_resolve.invoke(utils.clj:83)
	at leiningen.core.main$lookup_task_var.invoke(main.clj:68)
	at leiningen.core.main$pass_through_help_QMARK_.invoke(main.clj:78)
	at leiningen.core.main$task_args.invoke(main.clj:81)
	at leiningen.core.main$resolve_and_apply.invoke(main.clj:318)
	at leiningen.core.main$_main$fn__6160.invoke(main.clj:392)
	at leiningen.core.main$_main.doInvoke(main.clj:385)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at clojure.lang.Var.invoke(Var.java:401)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.main$main_opt.invoke(main.clj:315)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:186)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate clojure/data/priority_map__init.class or clojure/data/priority_map.clj on classpath: , compiling:(clojure/core/cache.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at stencil.loader$fn__11439.invoke(loader.clj:43)
	at stencil.loader__init.load(Unknown Source)
	at stencil.loader__init.<clinit>(Unknown Source)
	... 101 more
Caused by: java.io.FileNotFoundException: Could not locate clojure/data/priority_map__init.class or clojure/data/priority_map.clj on classpath: 
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core.cache$eval641$loading__4958__auto____642.invoke(cache.clj:9)
	at clojure.core.cache$eval641.invoke(cache.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	... 121 more
~~~

**Comment by sdegutis** [comment] 2015-05-05 19:33
This fixes it: `[lein-figwheel "0.3.1" :exclusions [org.clojure/core.cache]]`

**Comment by bhauman** [comment] 2015-05-06 13:23
This is normally caused by having a conflicting dependency in your `~/.lein/profiles.clj` please move that file and give it a try.

**Comment by sdegutis** [comment] 2015-05-06 13:31
@bhauman The only thing in that file was what was recommended by your readme:

~~~
$ cat .lein/profiles.clj 
{:user {:plugins [[lein-cljsbuild "1.0.5"]
                  [lein-figwheel "0.3.1"]]}}
~~~

**Comment by bhauman** [comment] 2015-05-06 13:37
So that wasn't what I was intending in the readme.  I was intending to have
that in the `project.clj`.  Please move that into the project.clj and give
it a try.

**Comment by sdegutis** [comment] 2015-05-06 13:46
@bhauman The line `lein new figwheel hello-world` implies that this goes into `~/.lein/profiles.clj` on account of there being no figwheel project yet to draw the figwheel plugin dependency from.

**Comment by bhauman** [comment] 2015-05-06 14:02
Actually that isn't true.  `lein new` finds the `fighweel-template` and
installs it for you.

The instructions are accurate.  I also highly recommend you try the Quick
Start.

Please remove the `profiles.clj` and try again with just `lein new figwheel
hello-world`

**Comment by dhruvbhatia** [comment] 2015-05-06 14:40
@sdegutis you probably had another dependancy that's using an older version of cache.
I had the same issue and had to do this to resolve:
```clojure
[clj-webdriver "0.6.1" :exclusions [org.clojure/core.cache]]
```

**Comment by bhauman** [comment] 2015-05-08 14:01
Closing this, until I here that there is actually a problem here.

**Closed by bhauman** 2015-05-08 14:01 UTC
