### ISSUE TITLE
Cannot read property 'cljs$lang$maxFixedArity' of undefined

### ISSUE THREAD

**Issue by sdegutis** [bhauman/lein-figwheel#145] opened 2015-05-05 20:09 UTC
Every time I reload my `.cljs` file, this error pops up in the browser's JS console.

**Comment by bensu** [comment] 2015-05-06 08:04
I can't reproduce this with a fresh project in Figwheel 0.3.1. Can you give us a little more context, like the file that is being loaded and your `project.clj`? This looks like a function call to an undefined function.

**Comment by bhauman** [comment] 2015-05-08 14:02
Closing this issue for lack of information.

**Comment by noonian** [comment] 2015-05-10 20:59
You will see this if you remove on-js-reload from your core file but leave `:on-jsload "example-app.core/on-js-reload"` in the :figwheel configuration section of cljsbuild. Removing that will stop the error but note that you must not remove the figwheel section completely or figwheel won't get injected into the compiled js. `:figwheel true` seems to work.

**Comment by bhauman** [comment] 2015-05-12 16:50
This needs to be fixed.  I will detect to see if the function is present and offer a helpful error message.

**Closed** 2015-05-12 18:31 UTC
Labels: bug
